name: publish
on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install data2objects with publish dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install -e .

      - name: Build
        run: python -m build

      - name: Check
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
